package org.infinispan.stats.container.transactional;

/**
 * Data access statistics. It is used in local context for transactional and non-transactional caches
 *
 * @author Pedro Ruivo
 * @since 6.0
 */
public enum DataAccessStatistics {
   //WRITE
   NUM_WRITE,
   WRITE_DUR,
   NUM_WRITE_FAIL_LOCK_TIMEOUT,
   WRITE_DUR_FAIL_LOCK_TIMEOUT,
   NUM_WRITE_FAIL_NETWORK_TIMEOUT,
   WRITE_DUR_FAIL_NETWORK_TIMEOUT,
   NUM_WRITE_FAIL_DEADLOCK,
   WRITE_DUR_FAIL_DEADLOCK,
   NUM_WRITE_FAIL_VALIDATION,
   WRITE_DUR_FAIL_VALIDATION,
   NUM_WRITE_FAIL_UNKNOWN,
   WRITE_DUR_FAIL_UNKNOWN,

   //READ
   NUM_READ,
   READ_DUR,
   NUM_READ_FAIL_LOCK_TIMEOUT,
   READ_DUR_FAIL_LOCK_TIMEOUT,
   NUM_READ_FAIL_NETWORK_TIMEOUT,
   READ_DUR_FAIL_NETWORK_TIMEOUT,
   NUM_READ_FAIL_DEADLOCK,
   READ_DUR_FAIL_DEADLOCK,
   NUM_READ_FAIL_VALIDATION,
   READ_DUR_FAIL_VALIDATION,
   NUM_READ_FAIL_UNKNOWN,
   READ_DUR_FAIL_UNKNOWN,
}
